# Generated by Django 5.1.5 on 2025-01-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photo'},
        ),
    ]
