# Generated by Django 5.1.5 on 2025-01-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service', models.CharField(choices=[('express', 'Экспресс-мойка (500 ₽)'), ('full', 'Полный комплекс (1500 ₽)'), ('detailing', 'Детейлинг (2500 ₽)')], max_length=20, verbose_name='Услуга')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
