# Generated by Django 5.1.5 on 2025-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайды'},
        ),
    ]
