# Generated by Django 5.1.5 on 2025-02-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.CreateModel(
            name='WashingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Место 1'), (2, 'Место 2'), (3, 'Место 3'), (4, 'Место 4'), (5, 'Место 5'), (6, 'Место 6'), (7, 'Место 7'), (8, 'Место 8'), (9, 'Место 9'), (10, 'Место 10')], verbose_name='Номер места')),
                ('service', models.CharField(choices=[('express', 'Экспресс-мойка (500 ₽)'), ('full', 'Полный комплекс (1500 ₽)'), ('detailing', 'Детейлинг (2500 ₽)')], max_length=20, verbose_name='Услуга')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Место для мойки',
                'verbose_name_plural': 'Места для мойки',
                'unique_together': {('number', 'service')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carwash.washingspot', verbose_name='Место'),
        ),
    ]
