# Generated by Django 5.1.5 on 2025-02-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car_model',
        ),
    ]
