# Generated by Django 5.1.5 on 2025-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0010_remove_profile_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Отвечено')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
